services:
  bot:
    image: witrixs/witrixdiscordbot:latest
    container_name: witrixdiscordbot
    restart: always
    env_file: .env
    network_mode: host
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - bot_data:/app/data

volumes:
  bot_data:
